### ISSUE TITLE
User creation fails for invalid XML user creation template

### ISSUE THREAD

**Issue by ITwerx** [ShMaunder/JMapMyLDAP#1]
After successfully using the previously available version2 of JMapMyLDAP tools, I recently upgraded to the newer version2 from the http://shmanic.com website updated on Dec 14th 2013. I was unable to successfully create a user with the newer version2 for the following error:

The XML user creation template '/etc/openldap.xml' is invalid.

Again, the previously available version2 worked (with a minor glitch of having to register twice). I followed all of the installation instructions, configured all of the plugins based on previous working settings, copied the example template .php and .xml files, and pointed the base directory to them. The only edit was done (necessarily) to the openldap.php file to contain the correct domain information. Other than that the .xml template file is exactly the same as the one i used for  the previously available version2.

Love this Joomla extension! Really need it for about half a dozen websites that need to authenticate via LDAP to Joomla, Subversion, and Redmine issue tracker. Will probably make a donation soon since we rely on it so heavily.

**Comment by ShMaunder** [comment]
Hmm, I'm going to guess its something to do with the domain changes made within the last month that allow multiple creation templates on the same site.

``` php
$this->domain = SHFactory::getConfig()->get('ldap.defaultconfig');
$xml->xpath("/templates/template[@domain='{$this->domain}']");
```

Does your XML domain match the default domain from "LDAP Settings" in com_shconfig?

The domain is labelled from the name given for each "LDAP Host Configuration". A default domain can be selected from com_shconfig (or the star icons in com_shldap) after creating the host configuration. This value must match the domain specified in the XML. I should add an error message if the XML is actually valid but default domain is not.

**Comment by ITwerx** [comment]
Thanks Shaun, I've double checked the name of the .xml file against the com_shconfig component, and the domain setting inside the xml file, and the LdapCreation_openldap setting in the .php helper. My LDAP testing works fine in com_shldap, so I know I'm binding and searching OK. One setting was wrong in the form for the Host Configuration. "All User Filter" (was (objectClass=Person) should have been objectClass=inetOrgPerson), but that didn't fix my problem. I'm going to double check all my settings again against a working older version2, but the fact that I'm binding and searching OK and failing for the creation template has me stumped. I have all debugging and info logging on, but the error above is all I have to report to you.

**Comment by ShMaunder** [comment]
Just to also double check, is that setting in com_shconfig the saved setting and not the default. Do you have a ldap.defaultconfig in the database entries and a yellow star next to the LDAP host? Only other thing is the domain is case sensitive and must match case in the XML.

I can't see any code changes other than the defaultconfig to affect XML reading. I'll take a closer look over the next few days.

**Comment by ITwerx** [comment]
Bingo, the yellow star was blank (not default). That fixed it! Not sure if that was an operator error or a bug. 

I am still having a minor error where i must register twice. The debug output shows a successful creation on the 1st attempt, and phpLDAPadmin shows that the user was created, but the Joomla UI claims that it failed. This is confirmed in the backend user manager. The 2nd attempt works, and the Joomla UI confirms success and the user is created in Joomla. I know this is a different bug than the one reported, and I can certainly open it as a new bug if you'd like. This happened on the previous version2 as well. I have played with the plugin ordering in Joomla, but it didn't help. any thoughts? Shall I open this issue also?

I'll be making a donation later tonight from one of my entities either ITwerx, or Bolder Software as well as putting a review in the Joomla extensions directory once I get home. Thanks again Shaun!

**Comment by ShMaunder** [comment]
Thanks, that is much appreciated! 

I've partly addressed the issue you originally with the XML had to make it clearer when issues happen with the domain in the logs. I will also commit a warning notice in the component to show when the default domain is not set.
