### ISSUE TITLE
Password Change Fails

### ISSUE THREAD

**Issue by jrseliga** [ShMaunder/JMapMyLDAP#15]
I have configured the Password and Injection plug-ins as described in the documentation for version 2, as well as updated the password attributes in the LDAP host configuration however, when attempting to reset a password through the Joomla frontend I receive the notice of "Profile could not be saved:"

Joomla 3.2.3
Shmanic Platform/Plugins: 2.0.1.16

**Comment by ShMaunder** [comment]
What LDAP server vendor are you using?

Does the ldap.debug.php log show anything (activated via "SHLog - LDAP" plug-in)?

**Comment by jrseliga** [comment]
Nothing is being logged to debug.
"An LDAP modify replace operation failed. (50) Insufficient access."

However, ldap.error.php logged:
12621   Failed to bind with proxy user.

Yet I'm able to login using LDAP

**Comment by ShMaunder** [comment]
You might be allowed to login if you are directly binding as the user using a DN (i.e. not using a LDAP search filter in the user query). The proxy user is used to do the actual password change. There is an option in the password plug-in to change the password with the same user, however this breaks the password change when a "current password" field isn't present (such as password reset, back-end password change, etc.).

**Comment by jrseliga** [comment]
I'm using: (sAMAccountName=[username])

The proxy user is a Domain Admin.

Even when I turn off the injection plugin, and disabled the option in the password plug-in it still fails.

**Comment by jrseliga** [comment]
When I turn off the Injection Plugin and disable the option in the Password plugin I get this error.

An LDAP modify replace operation failed. (53) Server is unwilling to perform.

**Comment by ShMaunder** [comment]
Hmm, I don't understand that proxy user error when you're using a LDAP query to successfully login.

Assuming you're using AD or Samba4, are you connecting using LDAP over SSL (LDAPS)?

**Comment by jrseliga** [comment]
Not using LDAPS

**Comment by ShMaunder** [comment]
At least with AD, you must be connecting with LDAPS to set passwords. It will fail otherwise.

**Comment by jrseliga** [comment]
I can connect to the LDAP server over port 389, however it doesn't bind over 636

**Comment by ShMaunder** [comment]
I'm going to assume that this was an issue with the LDAP server rather than an issue with JMapMyLDAP. There are several prerequisites that need to be performed on the LDAP server and web server to enable LDAPS (mainly related to certificates). I committed a890c5aeafa58406f89a6e518e5e14741afb97cf to help detect issues where host:port is not reachable which may help in situations like this. Closing.
