### ISSUE TITLE
Binding Fails after restore

### ISSUE THREAD

**Issue by jrseliga** [ShMaunder/JMapMyLDAP#17]
When restoring a Joomla installation (with JMapMyLDAP installed/configured), binding to that server fails.  The only workaround I have found is to uninstall/install JMapMyLDAP, and configure the same LDAP server again.

Is there a configuration setting that would prevent the binding from working after restore?

**Comment by ShMaunder** [comment]
Hi.

How are you doing the backup/restore? Direct SQL import or using something like Akeeba?

Also, what version of JMapMyLDAP are you referring to?

**Comment by ShMaunder** [comment]
Will close due to no reply.
