### ISSUE TITLE
Where is Group mapping in JmapMyLdap 2 ?

### ISSUE THREAD

**Issue by baptisteFX** [ShMaunder/JMapMyLDAP#2]
I can't see the group mapping as User - JmapMyLdap in Shmanic Config.
Help me please.

**Comment by ShMaunder** [comment]
Hi, 

There is no "User - JMapMyLDAP" plug-in in version 2 (only present in version 1).

To get group mapping in version 2, the "LDAP - Group Mapping" plug-in deals with it which can be installed from the pkg_ldap_plugins package.

Following through http://shmanic.com/tools/jmapmyldap/documentation/ver-2-getting-started.htm, http://shmanic.com/tools/jmapmyldap/documentation/ver-2-ldap-settings.htm and http://shmanic.com/tools/jmapmyldap/documentation/ver-2-mapping-plugin.htm should get you the full group mapping in version 2.

**Comment by baptisteFX** [comment]
Thank you very much !!
