### ISSUE TITLE
JArrayHelper in /libraries/shmanic/factory.php after J3.4 Update

### ISSUE THREAD

**Issue by nmo-hosting** [ShMaunder/JMapMyLDAP#31]
JArrayHelper::getValue is deprecated in J3.4. 
Example: In the factory.php in line 225:

if ($password = JArrayHelper::getValue($user, 'password', false))

quick fix:

if (is_array($user) && $password = JArrayHelper::getValue($user, 'password', false))

**Comment by ShMaunder** [comment]
Hi, please see #28 

I'm trying to get the fixed package tested ASAP and released.
