### ISSUE TITLE
LDAP query works but can't login in v2

### ISSUE THREAD

**Issue by zef79** [ShMaunder/JMapMyLDAP#43]
Hi All

Installed v1 and setup LDAP, everything worked perfectly

Disabled all plugins for v1, Setup v2, tested LDAP query with same settings as in v1, everything works, no errors and data is pulled back from LDAP in test/debug section.

Try to log into front end of server with same details and get error 
"Warning. Username and password do not match or you do not have an account yet."

Any ideas?

**Comment by terjerosenlund** [comment]
I don't know if my problem is the same but it seems related

My host configuration has LDAP V3 turned on and debug/test complains about 'Invalid Map User Id' and Invalid Map Email' but pulls all other information from ldap server (AD)
When logging in I receive a (different) message that says that I do not have access to private content
The result is the same on both front- and back-end

During debug I found that the username was reset inside function login() (cms.php, line 793) after calling: $authorisations = $authenticate->authorise($response, $options); (line 810)

Saving username in cms.php and restoring it after return from authorise() solved my problem but I guess it should be fixed elsewhere

**Comment by kirancheema** [comment]
Do you have the Authentication Plugin turned on?

**Comment by kirancheema** [comment]
@terjerosenlund did you try re-ordering The Joomla user Plugins?

**Comment by zef79** [comment]
I actually got it working
After disabling v1 and then re-enabling v2, it started working there last week, even though i didnt change anything, very odd
