### ISSUE TITLE
Adding any LDAP Host Configuration fails

### ISSUE THREAD

**Issue by felly** [ShMaunder/JMapMyLDAP#5]
When trying to create a new LDAP Host Configuration and saving the config it fails because of:

```
Warning
Invalid field: Name
```

Debugging Output works like a charm.

**Comment by ShMaunder** [comment]
What is the name you're trying to use for the LDAP host config? Does it work using a simple name such as "test"?

I'm currently away from the test environment so cannot check when that error message happens.

**Comment by felly** [comment]
Sry for the delay. 
No, it actually accepts nothing like that at all. I'm currently using `Joomla 3.2.1` and `Shmanic LDAP 2.0.0.400`

**Comment by ShMaunder** [comment]
Is this a fresh Joomla installation?

The regex on that field is `[A-Z0-9_\.-\s]+$` though I have just noticed that might be allowing bad characters in and actually should be `^[A-Z0-9_\.-\s]+$`, but as long as you're only tying those characters then it should work.

As the field validation is in a library, can you check the `System - Shmanic Platform` plug-in is enabled and the file `/libraries/shmanic/form/rules/ldapdomain.php` exists.

**Comment by felly** [comment]
Thanks for your help, everything worked fine on another server. Guess I need to dig into my server settings.
Sorry for the for the inconvenience I caused.

**Comment by greendome** [comment]
Hi Felly,

Sorry to comment on a closed issue...I'm having the same issue with LDAP config i.e. Invalid field: name. Are you able to advise what the fix was or how to go about troubleshooting it?

Thank you.

**Comment by ShMaunder** [comment]
This was a genuine issue - please see download link in one of the comments in https://github.com/ShMaunder/JMapMyLDAP/issues/13

**Comment by schubby** [comment]
I looked in the file /libraries/shmanic/form/rules/ldapdomain.php 

And i found this line   protected $regex = '[A-Z0-9_.-\s]+$';
I supposed so that we need to write the name in UPPERCASE but it didn't work

... Anybody have a better idea ? =/

**Comment by dtrencevski** [comment]
Fixed by going to C:\xampp\htdocs\YourJoomlaSite\libraries\shmanic\form\rules and edit the ldapdomain.php file. Replace [A-Z0-9_.-\s] with ^[^<>"\'%;()&\\

**Comment by savedario** [comment]
That $regex is a valid regular expression in Javascript but not in PHP.
I sort of interpreted the original intention and I used:
'[A-Z0-9_.][^\s]+$'
which works in both languages.
It means only letters, numbers, underscore and dots are allowed (no whitespace) and the modifier a few lines below makes it case insensitive.
