### ISSUE TITLE
CLI Import fails on Joomla 3.5

### ISSUE THREAD

**Issue by ssanfordamch** [ShMaunder/JMapMyLDAP#50]
PHP Notice:  Undefined index: HTTP_HOST in /var/www/default/libraries/joomla/application/web.php on line 869
PHP Stack trace:
PHP   1. {main}() /var/www/default/cli/ldap_cron.php:0
PHP   2. JApplicationCli->execute() /var/www/default/cli/ldap_cron.php:255
PHP   3. LdapCron->doExecute() /var/www/default/libraries/joomla/application/cli.php:141
PHP   4. JFactory::getApplication() /var/www/default/cli/ldap_cron.php:76
PHP   5. JApplicationCms::getInstance() /var/www/default/libraries/joomla/factory.php:125
PHP   6. JApplicationSite->__construct() /var/www/default/libraries/cms/application/cms.php:404
PHP   7. JApplicationCms->__construct() /var/www/default/libraries/cms/application/site.php:63
PHP   8. JApplicationWeb->__construct() /var/www/default/libraries/cms/application/cms.php:105
PHP   9. JApplicationWeb->loadSystemUris() /var/www/default/libraries/joomla/application/web.php:158
PHP  10. JApplicationWeb->detectRequestUri() /var/www/default/libraries/joomla/application/web.php:1113

Notice: Undefined index: HTTP_HOST in /var/www/default/libraries/joomla/application/web.php on line 869

Call Stack:
    0.0005     273952   1. {main}() /var/www/default/cli/ldap_cron.php:0
    0.0478    4833752   2. JApplicationCli->execute() /var/www/default/cli/ldap_cron.php:255
    0.0478    4835168   3. LdapCron->doExecute() /var/www/default/libraries/joomla/application/cli.php:141
    0.0478    4835536   4. JFactory::getApplication() /var/www/default/cli/ldap_cron.php:76
    0.0499    5204528   5. JApplicationCms::getInstance() /var/www/default/libraries/joomla/factory.php:125
    0.0508    5373064   6. JApplicationSite->__construct() /var/www/default/libraries/cms/application/cms.php:404
    0.0508    5373592   7. JApplicationCms->__construct() /var/www/default/libraries/cms/application/site.php:63
    0.0508    5373968   8. JApplicationWeb->__construct() /var/www/default/libraries/cms/application/cms.php:105
    0.0516    5453944   9. JApplicationWeb->loadSystemUris() /var/www/default/libraries/joomla/application/web.php:158
    0.0516    5454072  10. JApplicationWeb->detectRequestUri() /var/www/default/libraries/joomla/application/web.php:1113

Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by "/var/www/default/libraries/joomla/application/web.php" at line 869.

**Comment by conconnl** [comment]
We have the same problems.
When will this be fixed?

**Comment by Abthea** [comment]
yes, I have similiar problem too :

**Xampp 3.2.1
Windows Server 2012
Joomla 3.5.1
JMapMyLdap 2**

Notice: Undefined index: HTTP_HOST in C:\xampp\htdocs\PLANET\libraries\joomla\application\web.php on line 869
Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have alrea
dy been sent by "C:\xampp\htdocs\PLANET\libraries\joomla\application\web.php" at line 869.

**Comment by conconnl** [comment]
I solved the problem by downloaded the latest version of web.php from the Joomla GitHub repository

**Comment by Abthea** [comment]
Hi,

Could you pls give me the link the latest version web.php that you used

**Comment by conconnl** [comment]
In the Joomla Github Repository on the same location as on you website.
https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/application

**Comment by conconnl** [comment]
@ShMaunder this issue can be closed.
