### ISSUE TITLE
Ldap Profile -> Use Profile don't work with J3.6 anymore

### ISSUE THREAD

**Issue by ufuk-avcu** [ShMaunder/JMapMyLDAP#54]
Enviroment: Joomla 3.6.2 | JMapMyLDAP 2.0.3.1
Problem: No Network Profile Tab in the com_users edit view anymore, after J3.6.2 Update.

I try to debug this, but without success so far. I add a print_r($form) after this line https://github.com/ShMaunder/JMapMyLDAP/blob/master/plugins/ldap/profile/profile.php#L409 and the output shows me that the extra xml file is loaded. But no additional Tab appears in the Backend User view. Before the Joomla Update, i see an additional Tab with the "Network Profile" label. Anyone else the same issue?

**Comment by walliski** [comment]
I have problems with login in new users, seems as if it complains about invalid email and fails to create them. Could be something similar?

**Comment by conconnl** [comment]
@ufuk-avcu do you still have this problem with 3.6.5?
I want to start extending the profile part in the frontend, so maybe I can directly check if I can reproduce you error.

With a first test a made this possible.
Not sure if you meant missing this part.
<img width="1067" alt="screen shot 2017-01-21 at 00 17 18" src="https://cloud.githubusercontent.com/assets/11913918/22168738/1cde6fc2-df6f-11e6-9e61-3dcc0b61d7d5.png">


Regards, Wilco (The Netherlands)
See you soon

**Comment by ufuk-avcu** [comment]
@conconnl the problem was on our site. Somehow we had overrides in the Backend Template Isis. We changed that. The problem is solved! Thank you.
